// Default Labels
export enum LabelText {
  ADD_CATEGORY = 'Add category',
  COLLAPSE_CATEGORY = 'Collapse Category List',
  NOTES = 'Notes',
  CREATE_NEW_TEST_NOTE = 'Create new test note',
  DELETE_PERMANENTLY = 'Delete permanently',
  DOWNLOAD = 'Download',
  FAVORITES = 'Favorites',
  SCRATCHPAD = 'Scratchpad',
  MARK_AS_FAVORITE = 'Mark as favorite',
  MOVE_TO_TRASH = 'Move to trash',
  NEW_CATEGORY = 'New category...',
  NEW_TEST_NOTE = 'New test note',
  REMOVE_CATEGORY = 'Remove category',
  REMOVE_FAVORITE = 'Remove favorite',
  MOVE_CATEGORY = 'Move category',
  RESTORE_FROM_TRASH = 'Restore from trash',
  SETTINGS = 'Settings',
  SYNC_NOTES = 'Sync notes',
  TRASH = 'Trash',
  CONTACT = 'Contact',
  WELCOME_TO_TAKENOTE = 'Welcome to Takenote!',
  RENAME = 'Rename category',
  ADD_CONTENT_NOTE = 'Please add content to this new test note to access the menu options.',
  DOWNLOAD_ALL_NOTES = 'Download all notes',
  BACKUP_ALL_NOTES = 'Export backup',
  IMPORT_BACKUP = 'Import backup',
  TOGGLE_FAVORITE = 'Toggle favorite',
  COPY_REFERENCE_TO_NOTE = 'Copy reference to note',
}
